# the below option goes here and not in backend
# publish_mode: editorial_workflow ==> allows saving and editing of drafts - works like branch, commit to branch, respectively
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: dkemko1lp
    api_key: 221453993611229
    multiple: true
    max_files: 100
    # default_transformations: # makes f_auto and q_auto for all inserted
    #   - quality: auto
    #     fetch_format: auto
    # not sure how to get below to work yet but they're related to making the cloudinary widget more seamless
    # inline-container: "body"
    # remove_header: true

# Each collection can have extension and format options
# For example, you could set both to json to have new entries in the collection save as .json files instead of .md
# However, then you'd have to change your source plugin to be able to query the json files instead of MarkdownRemark
# Specifically, there's a source plugin called gatsby-transformer-json ! Try it out maybe!
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, allow_multiple: false}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "albums"
    label: "Albums"
    folder: "src/pages/albums"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "album-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      # allow_multiple doesn't seem to be supported by cloudinary!
      - {label: "Featured Image", name: "featuredimage", widget: "image", allow_multiple: false} 
      - {label: "Location", name: "location", widget: "map", required: false}
      - label: "Photos"
        name: "photos"
        widget: image
      - {label: "Tags", name: "tags", widget: "list", required: false}
